### PR TITLE
Binding "g C-g" to count words

### PR DESCRIPTION
**Pull request by condy0919**
`g C-g` to count words in motion state

### CODE REVIEW

**Comment by condy0919** [comment]
@TheBB This change is small enough.

**Comment by TheBB** [comment]
Thanks, but conventionally in Emacs, C-g should not be used as the final part of a key binding, because it is used for canceling. See [key binding conventions](http://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html).

When Vim defaults conflict with Emacs conventions we generally err on the side of Emacs conventions and leave a customization variable for people who want to override it (see all the other `evil-want-...` variables). It seems almost silly to do so here because this is such a minor binding, but we can call it `evil-want-C-g-bindings` and use it for all Vim bindings that use C-g, even if there's only one. What do you think?

**Comment by condy0919** [comment]
Fine with me

**Comment by TheBB** [comment]
Thanks!

**Pull request merged**
