### PR TITLE
Mention NonGNU ELPA

### PR DESCRIPTION
**Pull request by wasamasa**
See https://github.com/emacs-evil/evil/issues/1507.

### CODE REVIEW

**Review by tomdl89 — APPROVED** [review]

**Comment by phikal** [comment]
I apologize for noticing this somewhat late, but was it also intended to update the list of badges at the top of the README file?

**Comment by wasamasa** [comment]
I briefly considered to do that, but decided against it. Surely GNU stuff doesn't have badges, right?

**Comment by phikal** [comment]
Every ELPA package gets a badge generated:

badge

see http://elpa.nongnu.org/nongnu/evil.html.

A few packages are already using them. Personally I'm not a fan of the concept, but a few packages are already using them and posts like [these](https://www.reddit.com/r/emacs/comments/p181d3/is_there_any_plan_to_move_evil_to_nongnu_elpa/) indicate that it might be easy to miss if a package is available in a package repository just from textual documentation. That being said, there is of course no obligation to add it, I was just wanted to check.

**Comment by wasamasa** [comment]
Alright, I've added it.

**Pull request merged**
