### PR TITLE
Split evil-tests.el into two files

### PR DESCRIPTION
**Pull request by edkolev**
The new file evil-test-helpers.el can be used by evil plugin authors
to write tests in the same manner as evil-mode's tests.

Refs #846

### CODE REVIEW

**Comment by wasamasa** [comment]
This breaks `make`.  Is this intentional?  Full error:

```
make: *** No rule to make target 'evil-test-helpers.el,evil-types.el', needed by 'evil-test-helpers.el,evil-types.elc'.  Stop.
```

**Comment by edkolev** [comment]
It's not intentional - all make commands (`make test`, `make emacs`, etc) must not be affected. 

However, I can't reproduce the error. Maybe the `.depend` file needs to be recreated.

Could you please try to remove this file with `rm .depend`. `make clean` removes this file as well but I guess you won't be able to run it due to the error.

**Comment by TheBB** [comment]
As far as I'm aware the correct variant is

    FILES = $(filter-out evil-tests.el evil-test-helpers.el evil-pkg.el,$(wildcard evil*.el))

There doesn't need to be multiple `filter-out`s like before, and you need to use spaces instead of commas.

Hooray for stringly types.

**Comment by edkolev** [comment]
Thanks, I just amended the commit with the suggested change in the Makefile.

**Comment by wasamasa** [comment]
Thanks, this makes it build again.  The other thing sticking out here is that there is no `(require 'evil)` or `(require 'elt)` in the test file.  Technically, it's not needed, but it still seems wrong to me that it isn't there.

**Comment by edkolev** [comment]
OK, makes sense, the commit is amended.

I was thinking that it might be a good idea to make it obvious that `evil-test-buffer` is the only thing exported by `evil-test-helpers.el`. As a result, this file can be easily changed in the future while only trying to preserve this single macro's behaviour.

Should I rename the functions/macros in `evil-test-helpers.el` to make it obvious they are private? Maybe with a prefix `evil--...`.

**Comment by wasamasa** [comment]
Nah, exposed API is exposed API.  That aside, there's some candidates that are most likely used, like `evil-tests-initialize` (Makefile), `evil-with-temp-file` (evil-tests.el) and others.

Could it be that you cut off at the wrong point?  Everything from `evil-test-file-contents` shouldn't be in evil-test-helpers.el.

**Comment by edkolev** [comment]
I'll try to finish this PR within the following week, sorry for the delay, I've been busy.

**Comment by edkolev** [comment]
I finally had some time for this PR. I probably cut off at the wrong place last time. This time however, I started from scratch, moved `evil-test-buffer` to its own file, then moved its underlying functions to the new file.

I successfully managed to run some basic tests on an evil plugin using the `evil-test-buffer` macro from the newly created file.

**Comment by wasamasa** [comment]
Great, thanks!

**Pull request merged**
