### PR TITLE
Don't abort macro recording when current buffer is changed

### PR DESCRIPTION
**Pull request by edkolev**
Refs #847

### CODE REVIEW

**Comment by edkolev** [comment]
This PR removes `evil-abort-macro` which is aborts macro recording when the user switches to another buffer. Aborting on buffer change limits the usefulness of macros.

This function seems to be added in the first place to address this issue https://github.com/emacs-evil/evil/issues/568 however it doesn't seem relevant anymore.

**Comment by wasamasa** [comment]
Code looks good, what I'm mostly wondering about is the concerns voiced in the original ticket.  I know that keyboard macros are just keys, but if it's possible to enter undefined state, there'd need to be more precautions when recording them (such as resetting some variables upon a buffer change?).

**Comment by edkolev** [comment]
I played a bit with switching buffers while also recording a macro, plus leaving a buffer in insert state. However, I can't come up with a situation where evil misbehaves.

@wasamasa could you give me some guidelines what to try out to possibly break evil? If I can't reproduce evil entering an undefined state, I most probably won't be able to figure out what variables to reset.

**Comment by wasamasa** [comment]
Not really, no.  I guess we'll have to do it like with the search thing and fix it if people open issues for it.

**Comment by edkolev** [comment]
OK, I'll be keeping a close eye on any reported issues.

**Comment by wasamasa** [comment]
Alright, thanks.

**Pull request merged**
