### PR TITLE
Rewrite evil-ex-substitute

### LINKED ISSUE #824: Can't replace newlines with :s
OS: Linux Mint
Emacs version: 24.5.1
Evil version: f0684c1f6644a8c4e0e5fce50a1a04796555eaf1
Running GUI in X.

# Steps to reproduce.

1. `make emacs`
2. (All tests pass.)
3. In a buffer with
```
line1
line2
line3
```
4. Try to replace the newlines with the character a, by pressing `:%s/ C-q C-j /a/ RET`.
5. Observe the preview before pressing `RET`.

# Observed behavior

The preview is wrong. It looks like only the newlines after `line1` and `line3` (but not `line2`) are going to be replaced. When pressing `RET`, nothing changes, i.e. the buffer remains unchanged. Emacs says "Replaced 0 occurrences".

### PR DESCRIPTION
**Pull request by justbur**
New version of #825 which now fixes #824 and #811. 

I rewrote evil-ex-substitute to remove the call to `perform-replace` and to streamline the logic. 

I added the n flag as suggested by @edkolev in #811 and also took the liberty of adding support for the vim confirmation prompt which looks like
```
Replace a with b (y/n/a/q/l/^E/^Y)?
```
and includes the C-e and C-y keybindings like vim.

### CODE REVIEW

**Comment by wasamasa** [comment]
Wow, thanks! Behavior seems to be like previously, so far the only oddity I've run into is that I've managed to run into an odd state where typing `:s/\n/g/` displays a `[stringp]` message next to it in the echo area.  Trying to debug where exactly in `evil-ex-update-highlights` it came from undid the display of that message.

I've also noticed that in the same file the `(evil-ex-define-argument-type substitution ...)` call typo'd the `:expanded` property. Hopefully that's not the real cause of anything fixed in this PR?

Regarding code, the only thing sticking out so far is that markers aren't made to point nowhere after the command is done.  The elisp reference specially mentions that they can only be garbage-collected if they don't reference a buffer.  This can be done with `(move-marker my-marker nil)`.

**Comment by justbur** [comment]
> so far the only oddity I've run into is that I've managed to run into an odd state where typing :s/\n/g/ displays a [stringp] message next to it in the echo area. Trying to debug where exactly in evil-ex-update-highlights it came from undid the display of that message.

I'm not seeing that

> I've also noticed that in the same file the (evil-ex-define-argument-type substitution ...) call typo'd the :expanded property. Hopefully that's not the real cause of anything fixed in this PR?

I fixed that, but I'm not sure how that would affect things here.

> Regarding code, the only thing sticking out so far is that markers aren't made to point nowhere after the command is done. The elisp reference specially mentions that they can only be garbage-collected if they don't reference a buffer. This can be done with (move-marker my-marker nil).

Fixed, thanks

**Comment by wasamasa** [comment]
No issue, I'll put some debug prints into the code to catch it next time. Thanks again!

**Comment by wasamasa** [comment]
@justbur I've caught it this time, the culprit is the `(string= pattern "^")` in your new code.  `string=` is intended to be used on strings only and will error out on anything else (not 100% true, but close enough), `pattern` is a list of three elements and does therefore not work with this check.  I'd suggest you to improve the check, otherwise it's just dead code for an untested corner case.

**Comment by justbur** [comment]
@wasamasa you're absolutely right. See #836

**Pull request merged**
