### PR TITLE
Remove use of caddr in evil-test-helpers.el

### PR DESCRIPTION
**Pull request by justbur**
Also require cl-lib

### CODE REVIEW

**Comment by wasamasa** [comment]
Hum, wouldn't that also make the `(eval-when-compile (require 'cl))` in `evil-common.el` obsolete?  Other than that this looks good.

**Comment by justbur** [comment]
The test helpers don't get compiled usually, right? They're excluded from the melpa download for example.

**Comment by wasamasa** [comment]
Sure, it's just that I'd rather eliminate `cl` everywhere and from what I can tell, that particular line doesn't do anything because I cannot spot any of its macros in the file.

**Comment by justbur** [comment]
Well `cl` is included in `evil-jumps`. 

The issue is that `caddr` is not defined outside of `cl`. I can use emacs primitives instead of `cl-caddr`.

**Comment by wasamasa** [comment]
No, it's `cl-lib.el` which is fine. `cl` not so much, I'd like to avoid its use in our own code if possible.

**Comment by justbur** [comment]
Oh I think we’re talking about different things. Yes it seems that cl can be removed. Sorry I misinterpreted what you said.

**Comment by justbur** [comment]
@wasamasa I changed it to only use primitives

**Pull request closed without merging**
