### PR TITLE
evil-add-to-alist: convert to macro for lexical binding

### LINKED ISSUE #1270: Global markers are broken after lexical binding switch
# Issue type

- Bug report
# Environment

Emacs version: 27
Operating System: Linux
Evil version: used `make emacs` master ToT.
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)):Yes 

# Reproduction steps
- Start Emacs
`mT` fails with 

```
Debugger entered--Lisp error: (void-variable alist)
  symbol-value(alist)
  (let ((tail (symbol-value list-var))) (while (and tail (not (equal (car-safe (car-safe tail)) key))) (setq tail (cdr tail))) (if tail (setcar tail (cons key val)) (set list-var (append (symbol-value list-var) (list (cons key val))))) (if elements (apply #'evil-add-to-alist list-var elements) (symbol-value list-var)))
  evil-add-to-alist(alist 84 #<marker in no buffer>)
  (cond ((and marker (symbolp marker) (boundp marker)) (set marker (or (symbol-value marker) (make-marker))) (setq marker (symbol-value marker))) ((eq marker 'evil-jump-backward-swap) (evil-set-jump) (throw 'done nil)) ((functionp marker) (user-error "Cannot set special marker `%c'" char)) ((evil-global-marker-p char) (setq alist (default-value 'evil-markers-alist) marker (make-marker)) (evil-add-to-alist 'alist char marker) (progn (set-default 'evil-markers-alist alist))) (t (setq marker (make-marker)) (evil-add-to-alist 'evil-markers-alist char marker)))
  (if (markerp marker) nil (cond ((and marker (symbolp marker) (boundp marker)) (set marker (or (symbol-value marker) (make-marker))) (setq marker (symbol-value marker))) ((eq marker 'evil-jump-backward-swap) (evil-set-jump) (throw 'done nil)) ((functionp marker) (user-error "Cannot set special marker `%c'" char)) ((evil-global-marker-p char) (setq alist (default-value 'evil-markers-alist) marker (make-marker)) (evil-add-to-alist 'alist char marker) (progn (set-default 'evil-markers-alist alist))) (t (setq marker (make-marker)) (evil-add-to-alist 'evil-markers-alist char marker))))
  (let ((marker (evil-get-marker char t)) alist) (if (markerp marker) nil (cond ((and marker (symbolp marker) (boundp marker)) (set marker (or (symbol-value marker) (make-marker))) (setq marker (symbol-value marker))) ((eq marker 'evil-jump-backward-swap) (evil-set-jump) (throw 'done nil)) ((functionp marker) (user-error "Cannot set special marker `%c'" char)) ((evil-global-marker-p char) (setq alist (default-value 'evil-markers-alist) marker (make-marker)) (evil-add-to-alist 'alist char marker) (progn (set-default 'evil-markers-alist alist))) (t (setq marker (make-marker)) (evil-add-to-alist 'evil-markers-alist char marker)))) (add-hook 'kill-buffer-hook #'evil-swap-out-markers nil t) (set-marker-insertion-type marker advance) (set-marker marker (or pos (point))))
  (catch 'done (let ((marker (evil-get-marker char t)) alist) (if (markerp marker) nil (cond ((and marker (symbolp marker) (boundp marker)) (set marker (or (symbol-value marker) (make-marker))) (setq marker (symbol-value marker))) ((eq marker 'evil-jump-backward-swap) (evil-set-jump) (throw 'done nil)) ((functionp marker) (user-error "Cannot set special marker `%c'" char)) ((evil-global-marker-p char) (setq alist (default-value 'evil-markers-alist) marker (make-marker)) (evil-add-to-alist 'alist char marker) (progn (set-default 'evil-markers-alist alist))) (t (setq marker (make-marker)) (evil-add-to-alist 'evil-markers-alist char marker)))) (add-hook 'kill-buffer-hook #'evil-swap-out-markers nil t) (set-marker-insertion-type marker advance) (set-marker marker (or pos (point)))))
  evil-set-marker(84)
  funcall-interactively(evil-set-marker 84)
  call-interactively(evil-set-marker nil nil)
  command-execute(evil-set-marker)
```
# Further notes

The issue is that `evil-add-to-alist` no longer sees `alist` when lexical binding is on.

### PR DESCRIPTION
**Pull request by TheBB**
Fixes #1270

### CODE REVIEW

**Comment by yyoncho** [comment]
I just want to mention that hybrid-mode project does not use evil-add-to-alist directly but probably some of the evil-mode macros do use it and byte-compiled code keeps a reference to the evil-add-to-alist the function.

**Comment by TheBB** [comment]
Right. I guess I can use a macro with a different name.

**Comment by yyoncho** [comment]
As a side note the following piece of code is supposed to be the way to update alist:

```
(let ((foo '((bar . 100))))
  (setf (alist-get 'bar foo) 10)
  foo)

(let ((foo))
  (setf (alist-get 'bar foo) 10)
  foo)

```

**Comment by TheBB** [comment]
Yes, and the macro uses it for Emacs > 25.

`alist-get` was introduced in Emacs 25, but its comparison argument was only added in Emacs 26. Since `evil-add-to-alist` compares with `equal` rather than `eq` I am reluctant to change it for Emacs 25.

**Comment by agzam** [comment]
Can someone tell me please the status of this one? It's a bit of inconvenience to have to work without global markers. Thank you!

**Comment by TheBB** [comment]
Well, I just have other things I need to do sometimes.

Updated with a different macro name. Will merge if tests pass.

**Pull request merged**
