### PR TITLE
implement a flag for prohibiting the jump commands to switch buffers

### PR DESCRIPTION
**Pull request by c4eater**
This is a fix for #684.
It implements a new flag, evil-jumps-cross-buffers, which is allowing the user to switch to the old behavior.
Note, the current implementation is a bit sub-optimal, because when this option is set to false, every jump command basically makes Evil to filter out irrelevant jump marks from the jump list, and this is repeated over and over. Unfortunately, a more optimized implementation would significantly diverge from the original one (for it would require to completely refactor evil--jumps-window-jumps).

### CODE REVIEW

**Comment by Hi-Angel** [comment]
Original reporter here, tested, works for me.

**Comment by Hi-Angel** [comment]
Actually I found a small issue: open a file, search for the word under cursor with `*` *(so that it jumps to the next occurence)*, then press <kbd>C-o</kbd> to return where you were. It does only work for the second press, like if the first <kbd>C-o</kbd> gets eaten.

**Comment by Hi-Angel** [comment]
I found the problem. In `evil--jump-backward` the code


	+        (if (= idx -1)
	+            (progn
	+              (setq idx 0)
	+              (setf (evil-jumps-struct-idx struct) 0)
	+              (evil--jumps-push))
	+          (evil--jumps-jump idx 1))))))

should actually be 

	+        (when (= idx -1)
	+            (progn
	+              (setq idx 0)
	+              (setf (evil-jumps-struct-idx struct) 0)
	+              (evil--jumps-push)))
	+        (evil--jumps-jump idx 1)))))

I don't see problems with `evil--jump-forward`, but I guess it's the same.

As I'm not sure about the last one, I think I'll make the changes locally, and will try to use it for a few days. If everything is okay, I'll send my t-b.

**Comment by Hi-Angel** [comment]
Alternatively somebody more acknowledgeable about Evil's internals might just say what are the changes in the `jump-forward` and the `jump-backward` for.

**Comment by wasamasa** [comment]
Um, have you updated yet?  This is what I have on master:

```elisp
(defun evil--jump-backward (count)
  (let ((count (or count 1)))
    (evil-motion-loop (nil count)
      (let* ((struct (evil--jumps-get-current))
             (idx (evil-jumps-struct-idx struct)))
        (evil--jumps-message "jumping back %s" idx)
        (when (= idx -1)
          (setq idx (+ idx 1))
          (setf (evil-jumps-struct-idx struct) 0)
          (evil--jumps-push))
        (evil--jumps-jump-to-index (+ idx 1))))))
```

**Comment by Hi-Angel** [comment]
@wasamasa I was referring to modifications the patch making :)

**Comment by wasamasa** [comment]
Well, no idea, you'd have to ask its author about that.  If you make a PR that does better than this one, I'll close this thread in favor of it.

**Comment by c4eater** [comment]
Thanks for your feedback @Hi-Angel,

Your assumption is correct. When I was using the "if" construct, evil--jumps-jump hasn't been called on first visit. One minor update to your proposed code is that I'd like to remove the progn construct as "when" makes "progn" unnecessary.

Just updated the pull request.

**Comment by Hi-Angel** [comment]
Great, thank you! The series

Tested-by: Constantine Kharlamov <Hi-Angel@yandex.ru>

Please can anybody push the code?

**Comment by wasamasa** [comment]
@c4eater Thanks for the update.  From quick testing nothing seems to be broken with this change, both with and without the customizable enabled.

**Pull request merged**
