### PR TITLE
Map <C-w> q to evil-quit

### LINKED ISSUE #887: C-w q undefined
# Issue type
- Bug report: C-w q does not work like in Vim.

# Environment
Emacs version: GNU Emacs 25.2.1 (x86_64-w64-mingw32) of 2017-04-24
Operating System: Windows 10 (Also tested on Windows 7)
Evil version: 1.2.12
Evil installation type: Cloned from github
Graphical/Terminal: Graphical

# Reproduction steps
- Start Emacs (with evil-mode enabled)
- Press C-w v
- Press C-w q
- Press C-w q

# Expected behavior
At the first press of C-w q the window with the cursor closes, leaving only one window.
At the second press of C-w q the whole frame closes.

# Actual behavior
Minibuffer shows "C-w q is undefined".

# Further notes
For the Vim documentation about this command type ":help CTRL-w_q" in Vim.

### PR DESCRIPTION
**Pull request by hkgit03**
fix #887

### CODE REVIEW

**Comment by hkgit03** [comment]
I am not sure if `evil-quit` is the correct function to use. It does not seem to care about unsaved changes. Also, the Vim documentation for CTRL-w_q specifies `{count}` which is used to reference which window to close.

**Comment by wasamasa** [comment]
Congrats to PR #888!

Looks good to me.  The Vim help shows that `C-w q` and `:quit` end up calling the same thing.  To fix the problem of `C-w q` being unbound, this PR does just the right thing, taking a count argument into account is something I'd leave for another PR.

**Comment by hkgit03** [comment]
Thanks.
The unsaved changes thing would be also not be part of this issue, but an issue concerning the function `evil-quit`.

**Comment by wasamasa** [comment]
Correct.  I'll therefore merge this one and leave it up to whoever wants to provide the rest.

**Pull request merged**
