### PR TITLE
Fix up evil-indent

### PR DESCRIPTION
**Pull request by rbrtb**

### CODE REVIEW

**Comment by tomdl89** [comment]
Thanks for the PR. I'll need a description or (preferably) tests before I can merge @rbrtb

**Comment by rbrtb** [comment]
Test added.

**Comment by tomdl89** [comment]
Thanks for the test @rbrtb but that test passes _without_ your code change. I don't understand what your PR is trying to _fix_ so either I need a test which fails before and passes afterwards, or an explanation to that effect.

**Comment by rbrtb** [comment]
It seems that the test cannot pass without the change on my machine though (Emacs 28):
```
F evil-test-indent
    Test ‘evil-indent’
    (args-out-of-range 36 1 32)
```
And this PR is trying to fix that, when the whole buffer is selected for `evil-indent`, the `indent-region` call may shrink the buffer so that the previous saved `end` is larger than `(point-max)`

**Comment by rbrtb** [comment]
I noticed my original test won't pass even after the change in `make test` though.(It did pass in my Emacs setup)
So it's updated.

**Comment by rbrtb** [comment]
Is it ok to merge this? @tomdl89

**Comment by tomdl89** [comment]
Yup - I understand now. Thanks for the PR @rbrtb 🚀

**Pull request merged**
