### PR TITLE
Some more improvements for evil-define-key

### PR DESCRIPTION
**Pull request by justbur**
Mention the effect of a `nil` state in docstring and give a meaning to using `nil` with `'global` or `'local`.

Handle errors in `evil-define-key` by wrapping definitions in `condition-case-unless-debug`.

### CODE REVIEW

**Comment by wasamasa** [comment]
Thanks! I'm currently testing the new functionality and stuff like `(evil-define-key '(motion visual) nil "SPC" 'butterfly)` doesn't work.  If I look at the expansion, it defines an `evil-define-key-in-nil` function which looks wrong to me, perhaps it would be better to use `make-symbol` instead.

**Comment by justbur** [comment]
Agree we could improve the function name, but the problem with your example is you need to wrap that key with `kbd`.

**Comment by justbur** [comment]
Oh and nil is not a valid keymap

**Comment by wasamasa** [comment]
Oh duh. I guess what I want is `(evil-define-key* '(motion visual) 'global (kbd "RET") 'butterfly)` which works as expected, however `(evil-define-key '(motion visual) 'global (kbd "RET") 'butterfly)` doesn't.  What's going wrong here?

**Comment by justbur** [comment]
> however `(evil-define-key '(motion visual) 'global (kbd "SPC") 'butterfly)` doesn't. What's going wrong here?

Nothing as far as I can tell. That works for me.

**Comment by wasamasa** [comment]
Sorry, I didn't apply the patch correctly. Anyway, the only thing missing now is that this added one more warning to the byte-compilation output.  You're referencing `local-set-key`, but didn't adapt it correctly as you're setting an unbound `map` argument.

**Comment by justbur** [comment]
@wasamasa Thanks, I overlooked that. I think it's correct now. Note that I did an interactive rebase and force pushed.

**Comment by wasamasa** [comment]
Alright.

**Pull request merged**
