### PR TITLE
Change evil-goto-definition to use a hook

### PR DESCRIPTION
**Pull request by wasamasa**
See also https://github.com/emacs-evil/evil/pull/869#issuecomment-314392574

### CODE REVIEW

**Comment by TheBB** [comment]
We did something similar to this in Spacemacs, and it turned out to be much less useful than we thought because so many find-definition implementations are asynchronous, and thus can't indicate success or failure in the return value. I'm curious if anyone has any solution to this that doesn't involve a lot more complications.

**Comment by wasamasa** [comment]
Can you give an example for asynchronous ones?  I find using `run-hook-with-args-until-success` a rather elegant solution and until Emacs gets futures/promises, I can't imagine anything elegant for asynchronous functions.

**Comment by TheBB** [comment]
Currently in Spacemacs there seems to be `ycmd-goto`, `tern-find-definition`, `omnisharp-go-to-definition`, `eclim-java-find-declaration` and `anaconda-mode-find-definitions` from various packages. I haven't looked at them all in detail. What we did was to force-abort the on asynchronous ones on the assumption that language servers are typically powerful enough not to fail to find things.

**Comment by joehillen** [comment]
I agree with @Hi-Angel in the previous thread that a position would be a better argument.

Sometimes a string can refer to different definitions based on context. It's not safe to assume that all instances of a string have the same definition. It might not even be correct that the occurrence at the top of the buffer is the definition.

Maybe a compromise would be to include both STRING and POSITION as arguments.

**Comment by edkolev** [comment]
I don't see how the position will be used - both imenu and xref take strings as input. I'm not sure about semantic, I haven't used it.

**Comment by wasamasa** [comment]
@joehillen This is a compromise I can live with.  Using point exclusively is inacceptable as it makes nearly every user of this hook look up the word at point, using it as additional argument makes it a minor annoyance that can be ignored in the argument list.

**Pull request merged**
