### PR TITLE
Add option to switch to undo-fu

### PR DESCRIPTION
**Pull request by TheBB**
Just a draft branch that I'll be playing around with for a while. Opening this as a heads up.

Hopefully this can end up closing #1074, #418 and #522.

### CODE REVIEW

**Comment by edkolev** [comment]
Nice initiative!

A couple of notes:
- let me know if you need need me to dogfood this feature - I'd be happy to test
- supporting both undo-tree and undo-fu might be a stretch (in terms of implementation cost, and maintenance cost). I suggest supporting just one one them

**Comment by TheBB** [comment]
Yeah I'd love for others to test.

Wasn't sure yet whether I wanted to rip out undo-tree completely or what. If testing goes well we can take that into account. One problem is that undo-fu has very strict Emacs version requirement. I'll check with the author if that's just because it's untested on older versions.

**Comment by TheBB** [comment]
Also *goto-chg* depends on undo-tree but I think it's a soft dependency.

**Comment by TheBB** [comment]
There's been a new release to undo-tree, which might mitigate some of the problems people have been seeing. I'll leave this PR in limbo for a while.

**Comment by jixiuf** [comment]
I would got  on emacs28 
```
Symbol's function definition is void: undo-tree-save-history-from-hook
```
I think  this hooks should be added after function is defined 
```
(add-hook 'write-file-functions #'undo-tree-save-history-from-hook)
(add-hook 'kill-buffer-hook #'undo-tree-save-history-from-hook)
(add-hook 'find-file-hook #'undo-tree-load-history-from-hook)
```

can not reach the author of undo-tree

**Comment by aaronjensen** [comment]
@jixiuf he responds to email, which you can find on his website: http://www.dr-qubit.org/undo-tree.html

That said, I think he is unlikely to make any changes for Emacs28 unless they are totally innocuous for current emacs versions.

The error you're seeing is surprising... they're changing the semantics of `#'symbol` or `add-hook` is doing validation now...

**Comment by TheBB** [comment]
I already reported that to him. I got a fixed version by email but nothing
on git or ELPA yet. If someone else wants to bump it be my guest!

**Comment by TheBB** [comment]
Undo-tree 0.7.3 is now out and it should have fixed the above mentioned issue.

**Comment by ideasman42** [comment]
Any update on this?

Even in the case undo-tree is has been fixed, it's a fairly large and complex package, it installs hooks even when it's disabled.
It would be nice if there was a way to disable undo-tree in evil mode.

```
(add-hook 'post-gc-hook #'undo-tree-post-gc nil)
;; --- snip --- 
(add-hook 'write-file-functions #'undo-tree-save-history-from-hook)
(add-hook 'kill-buffer-hook #'undo-tree-save-history-from-hook)
(add-hook 'find-file-hook #'undo-tree-load-history-from-hook)
 ```
----

Undo-fu by comparison:

- doesn't install any hooks/advice/timers.
- it's 230-SLOC compared to 2740-SLOC.
- no GC / undo-data manipulation.
- no extra mode/state needed It just exposes undo and redo which operate on Emacs undo information.

**Comment by TheBB** [comment]
No updates yet. I wrote this to try undo-fu but at that time there were still bugs. Since then undo-tree received a promising update, so I decided I could focus on other things for the moment.

I'll get around to it eventually, but of course if someone else wants to implement it I'd be happy to review and merge.

I'm pretty sure I actually do want the provider variable though. :smile:

**Comment by TheBB** [comment]
Note: we also need to double check that goto-chg works fine when undo-tree isn't present. It's supposed to, but since evil for the moment requires undo-tree I'm not sure how much those code paths have been tested.

**Comment by ideasman42** [comment]
Testing `goto-last-change` and `goto-last-change-reverse`, they both seem to be working properly.

**Comment by condy0919** [comment]
Any updates?

**Comment by TheBB** [comment]
If there's significant interest in an option for choosing undo provider please feel free to clean up the PR and resubmit. I don't have much time for evil at the moment. I've received no reports of bugs in the newer undo-tree versions so I don't consider it a priority.

**Comment by wasamasa** [comment]
@jixiuf @aaronjensen Do you have a minimal reproduction example for that change in hook functions? I've tried the following on Emacs built from master and failed to reproduce it with the following in a file:

```elisp
(defun my-test () (message "Test"))
(add-hook 'post-command-hook 'my-test)
```

**Comment by TheBB** [comment]
Closed in favor of #1360

**Pull request closed without merging**
