### PR TITLE
Add option to enable Evil in minibuffer(s)

### PR DESCRIPTION
**Pull request by Alexander-Shukaev**
Time to share the goodie which was for a long time in my private version of Evil.  I saw a number of people on the web looking for this support.  Enjoy!

### CODE REVIEW

**Comment by Alexander-Shukaev** [comment]
A friendly ping for a review.

**Comment by TheBB** [comment]
Hi, sorry for the delay. I'll have a look at your PRs this week.

**Comment by TheBB** [comment]
This looks like it works quite well. Thank you!

**Comment by TheBB** [comment]
Yep, see https://github.com/emacs-evil/evil/issues/945

**Pull request merged**
