### PR TITLE
Fixup f005120 Fix edge case with evil-search highlighting

### PR DESCRIPTION
**Pull request by justbur**
pattern is an object. We need to get the regex first.

See #832

### CODE REVIEW

**Comment by wasamasa** [comment]
Thanks!  You think this can be tested meaningfully or it's not worth it adding a regression test?

**Comment by justbur** [comment]
It would be nice to test it I guess, but I'm not sure how to test interactive highlighting like this. Since it's a visual thing, I see it as less important.

**Comment by wasamasa** [comment]
Alright, I've found a different visual glitch in the meantime, but will open a separate issue for it.

**Comment by wasamasa** [comment]
Hm, can't reproduce it again.

**Pull request merged**
