### PR TITLE
Fixes #1322: take tab-line height into account

### LINKED ISSUE #1322: Yet another bug with evil-scroll-up, causing by tab-line
The very same problem as #713, #965, and #1063, but it's a problem with `tab-line` in Emacs 27 rather than `header-line`. See also a merged PR that almost fixed the problem and my merged PR that also fixed the problem: #1154 and #1238.

# Issue type
- Bug report

# Environment

Emacs version: GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin19.4.0, NS appkit-1894.40 Version 10.15.4 (Build 19E287)) of 2020-06-07

Operating System: macOS Catalina
Evil version: Evil version 1.14.0
Evil installation type: via Doom Emacs
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps

- Open a file whose content doesn't fit the screen
- `C-u` and `C-d` from the top of the file to the bottom of the file and vice versa.

# Expected behavior
It scrolls normally.

# Actual behavior

```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  evil-scroll-down(nil)
  funcall-interactively(evil-scroll-down nil)
  call-interactively(evil-scroll-down nil nil)
  command-execute(evil-scroll-down)
```

### PR DESCRIPTION
**Pull request by sorawee**

### CODE REVIEW

**Comment by sorawee** [comment]
It's been a month, so I would like to bump the PR. There's no rush though. I understand that everyone is busy.

**Comment by sorawee** [comment]
Another friendly ping :)

**Comment by sorawee** [comment]
Yet another friendly ping :)

**Comment by countvajhula** [comment]
Thank you for this fix 🏅 . I tried it locally and can confirm that the problem is fixed in my environment (MacOS High Sierra, vanilla Emacs 27.1).

**Comment by sorawee** [comment]
Yeah, Evil maintainers seem to be busy. It's been six months already though, so maybe it's worth pinging some maintainers (@TheBB ?) directly in case they missed the notifications.

**Comment by sorawee** [comment]
@TheBB ping?

**Comment by sorawee** [comment]
Can we merge this? @tomdl89

**Comment by tomdl89** [comment]
I'll take a look when I have a minute. Sorry evil is not fully maintained right now!

**Pull request merged**
