### PR TITLE
Fix 1365: Respect nil `evil-kill-on-visual-paste'

### LINKED ISSUE #1365: Paste over visual does not register the replaced text like vim
# Bug (may be)

- Bug report

# Environment

Emacs version: 27.1
Operating System: Archlinux, kernel 5.8.13
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: Both GUI and in terminal
Tested in a `make emacs`: No, I use the emacs provided by Archlinux

# Reproduction steps

- Start Emacs: emacs -Q

When pressing `p` to paste text over a visual text, that visual text is replaced but not saved to the register.

Check variable: evil-kill-on-visual-paste, and it is "t".

# Expected behavior:

The  replaced text should be registered for the next paste.

# Actual behavior:

The replaced text is deleted.

# Further notes:

I notice that it was ok --like vim-- in the past. So I believe it is a bug of some newer evil version

### PR DESCRIPTION
**Pull request by tomdl89**
Fix #1365

### CODE REVIEW

**Comment by tomdl89** [comment]
Is there anything more needed to get this merged? Thanks

**Comment by tomdl89** [comment]
bump

**Comment by rettakjak** [comment]
Unfortunately Evil doesn't seem to be very active right now.  Like others, I also have some PRs (#1327, #1329, #1332) that have been sitting for several months now.

**Comment by TheBB** [comment]
Yes unfortunately evil is not so high on my list. Your PRs are not
forgotten though! I see every bump and feel bad each time. :-)

I'm happy to add collaborators by the way.

**Comment by tomdl89** [comment]
I'd be super interested in becoming a collaborator, although - like you - I have ups and downs in time availability. Don't feel bad when you see the bumps - it's just a friendly reminder :)

**Comment by rettakjak** [comment]
Same here regarding time availability, etc.  I hope my comment didn't come across as rude because all of this is totally understandable.

I would like to help Evil more too, but I'm still an Emacs/Evil newbie.

**Comment by tomdl89** [comment]
Hey @TheBB any progress on this? I'm keen to tackle a few more of the issues, but I'm worried my PRs won't get merged. If I'm being too impatient do say so - otherwise let me know how I can get more involved in collaboration. Thanks!

**Comment by TheBB** [comment]
Thanks! Sorry for the delay.

**Pull request merged**
