### PR TITLE
Add support for passing REGISTER and COUNT to :yank

### PR DESCRIPTION
**Pull request by edkolev**

### CODE REVIEW

**Comment by edkolev** [comment]
I don't consider this completely ready yet due to two things:

1. I haven't found a good way to abstract this piece of code which is now duplicated in `evil-ex-yank` and `evil-ex-delete`:
```
+  (when count
+    (setq beg (save-excursion
+                (goto-char end)
+                (forward-line -1)
+                (point))
+          end (save-excursion
+                (goto-char end)
+                (point-at-bol count))
+          type 'line))
+
```

Two solutions come to my mind:
- wrap it in a macro, then both `evil-ex-delete` and `evil-ex-yank` will call this macro
- use a `let*` and a new function `evil-ex-normalize-range-with-count`, something like:
```
(let* ((normalized-beg-end-type (evil-ex-normalize-range-with-count count end)
        (beg (car normalized-beg-end-type))
        (end (cdrr normalized-beg-end-type))
        (type (nth 2 normalized-beg-end-type))
        ....
)
```

Both options don't seem like an elegant solution.

2. The other issue is that with the newly added interactive code `<xc/>` the tests fail on OSX when run in terminal (they run fine on linux). There's no error on failure, just random text gets printed and a "emacs quite unexpectedly" message is displayed.

With some other random interactive code like `<o/>` works fine.

I'll try to figure out `2`. Any suggestions on how `1` or the PR can be improved are appreciated.

**Comment by wasamasa** [comment]
1. No need for a macro here.  What I'd do is converting the whole body into a higher-order function taking either `evil-delete` or `evil-yank` as argument (or even simpler, a boolean flag), then use funcall with the correct function and the remaining arguments.  Use that helper in `evil-ex-yank` and `evil-ex-delete`.
2. Interesting, my first hunch is that you've somehow invoked problematic functionality.  Can you run it with a debugger attached and retrieve a segfault?

**Comment by edkolev** [comment]
Thanks, now `evil-ex-delete` looks like this:
```emacs-lisp
(evil-define-operator evil-ex-delete (beg end type register count yank-handler)
   "The Ex delete command.
 \[BEG,END]delete [REGISTER] [COUNT]"
   (interactive "<R><xc/><y>")
   (evil-ex-delete-or-yank t beg end type register count yank-handler))
```

And `evil-ex-yank` just passes `nil` to the helper function.

**Comment by edkolev** [comment]
Regarding the second issue - I can't reproduce it every time. When running tests in the terminal, emacs almost always segfaults. When running the tests in GUI, the tests occasionally fail with this ert test (no segfault in GUI):

```
F evil-test-repeat-visual-char
    Test repeat of character visual mode command.
    Info: Test repeat on several lines
    (user-error "Cannot delete buffer in repeat command")
```

I'll investigate more, run with `lldb` attached, and share here.

**Comment by wasamasa** [comment]
Hm, might be the same as the segfaults in CI then.  I've once disassembled the output with `addr2line` on the used Emacs instance, `btrace` and a corresponding tarball of the sources:

```
#!/bin/sh --
# btrace - convert addr2line output into annotated backtrace

context=${1:-3}

while IFS=: read -r file lineno _; do
    printf '%s\n' "$file"

    if [ -e "$file" ]; then
        awk -v line="$lineno" -v ctx="$context" '
            NR > line - ctx && NR != line && NR < line + ctx { print " ", $0 };
            NR == line { print "=>"$0 }
        ' "$file"
    fi
done
```

```
/home/wasa/code/emacsen/emacs-24.5/src/sysdep.c
      }
  
=>  if (npointers)
      {
        emacs_write (STDERR_FILENO, "\nBacktrace:\n", 12);
/home/wasa/code/emacsen/emacs-24.5/src/emacs.c
    {
      sigset_t unblocked;
=>    sigemptyset (&unblocked);
      sigaddset (&unblocked, sig);
      pthread_sigmask (SIG_UNBLOCK, &unblocked, 0);
/home/wasa/code/emacsen/emacs-24.5/src/sysdep.c
  handle_fatal_signal (int sig)
  {
=>  terminate_due_to_signal (sig, 40);
  }
  
/home/wasa/code/emacsen/emacs-24.5/src/sysdep.c
  #endif
  
=>  handler (sig);
    errno = old_errno;
  }
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
       enabled, GC aborts if it seems to have visited an interval twice.  */
    eassert (!i->gcmarkbit);
=>  i->gcmarkbit = 1;
    mark_object (i->plist);
  }
/home/wasa/code/emacsen/emacs-24.5/src/intervals.c
      {
        (*function) (tree, arg);
=>      if (!tree->right)
  	tree = tree->left;
        else
/home/wasa/code/emacsen/emacs-24.5/src/intervals.c
  	{
  	  traverse_intervals_noorder (tree->left, function, arg);
=>	  tree = tree->right;
  	}
      }
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	    struct glyph *end_glyph = glyph + row->used[area];
  
=>	    for (; glyph < end_glyph; ++glyph)
  	      if (STRINGP (glyph->object)
  		  && !STRING_MARKED_P (XSTRING (glyph->object)))
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  		{
  		  mark_glyph_matrix (w->current_matrix);
=>		  mark_glyph_matrix (w->desired_matrix);
  		}
  
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
       The distinction is used e.g. by Lisp_Process which places extra
       non-Lisp_Object fields at the end of the structure...  */
    for (i = 0; i < size; i++) /* ...and then mark its elements.  */
      mark_object (ptr->contents[i]);
  }
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  		 matrices is sufficient because frame matrices
  		 use the same glyph memory.  */
=>	      if (w->current_matrix)
  		{
  		  mark_glyph_matrix (w->current_matrix);
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
       The distinction is used e.g. by Lisp_Process which places extra
       non-Lisp_Object fields at the end of the structure...  */
    for (i = 0; i < size; i++) /* ...and then mark its elements.  */
      mark_object (ptr->contents[i]);
  }
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  
  	      mark_vectorlike (ptr);
=>	      mark_face_cache (f->face_cache);
  #ifdef HAVE_WINDOW_SYSTEM
  	      if (FRAME_WINDOW_P (f) && FRAME_X_OUTPUT (f))
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
       The distinction is used e.g. by Lisp_Process which places extra
       non-Lisp_Object fields at the end of the structure...  */
    for (i = 0; i < size; i++) /* ...and then mark its elements.  */
      mark_object (ptr->contents[i]);
  }
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  		 matrices is sufficient because frame matrices
  		 use the same glyph memory.  */
=>	      if (w->current_matrix)
  		{
  		  mark_glyph_matrix (w->current_matrix);
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
       The distinction is used e.g. by Lisp_Process which places extra
       non-Lisp_Object fields at the end of the structure...  */
    for (i = 0; i < size; i++) /* ...and then mark its elements.  */
      mark_object (ptr->contents[i]);
  }
/home/wasa/code/emacsen/emacs-24.5/src/lisp.h
  LISP_MACRO_DEFUN (XFASTINT, EMACS_INT, (Lisp_Object a), (a))
  LISP_MACRO_DEFUN (XTYPE, enum Lisp_Type, (Lisp_Object a), (a))
=>LISP_MACRO_DEFUN (XUNTAG, void *, (Lisp_Object a, int type), (a, type))
  
  #else /* ! USE_LSB_TAG */
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	ptr->gcmarkbit = 1;
  	mark_object (ptr->function);
=>	mark_object (ptr->plist);
  	switch (ptr->redirect)
  	  {
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
       The distinction is used e.g. by Lisp_Process which places extra
       non-Lisp_Object fields at the end of the structure...  */
    for (i = 0; i < size; i++) /* ...and then mark its elements.  */
      mark_object (ptr->contents[i]);
  }
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	ptr->gcmarkbit = 1;
  	mark_object (ptr->function);
=>	mark_object (ptr->plist);
  	switch (ptr->redirect)
  	  {
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
       The distinction is used e.g. by Lisp_Process which places extra
       non-Lisp_Object fields at the end of the structure...  */
    for (i = 0; i < size; i++) /* ...and then mark its elements.  */
      mark_object (ptr->contents[i]);
  }
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	ptr->gcmarkbit = 1;
  	mark_object (ptr->function);
=>	mark_object (ptr->plist);
  	switch (ptr->redirect)
  	  {
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
       The distinction is used e.g. by Lisp_Process which places extra
       non-Lisp_Object fields at the end of the structure...  */
    for (i = 0; i < size; i++) /* ...and then mark its elements.  */
      mark_object (ptr->contents[i]);
  }
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	ptr->gcmarkbit = 1;
  	mark_object (ptr->function);
=>	mark_object (ptr->plist);
  	switch (ptr->redirect)
  	  {
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
       The distinction is used e.g. by Lisp_Process which places extra
       non-Lisp_Object fields at the end of the structure...  */
    for (i = 0; i < size; i++) /* ...and then mark its elements.  */
      mark_object (ptr->contents[i]);
  }
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	ptr->gcmarkbit = 1;
  	mark_object (ptr->function);
=>	mark_object (ptr->plist);
  	switch (ptr->redirect)
  	  {
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
       The distinction is used e.g. by Lisp_Process which places extra
       non-Lisp_Object fields at the end of the structure...  */
    for (i = 0; i < size; i++) /* ...and then mark its elements.  */
      mark_object (ptr->contents[i]);
  }
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	ptr->gcmarkbit = 1;
  	mark_object (ptr->function);
=>	mark_object (ptr->plist);
  	switch (ptr->redirect)
  	  {
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	obj = ptr->u.cdr;
  	cdr_count++;
=>	if (cdr_count == mark_object_loop_halt)
  	  emacs_abort ();
  	goto loop;
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	obj = ptr->u.cdr;
  	cdr_count++;
=>	if (cdr_count == mark_object_loop_halt)
  	  emacs_abort ();
  	goto loop;
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	ptr->gcmarkbit = 1;
  	mark_object (ptr->function);
=>	mark_object (ptr->plist);
  	switch (ptr->redirect)
  	  {
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	obj = ptr->u.cdr;
  	cdr_count++;
=>	if (cdr_count == mark_object_loop_halt)
  	  emacs_abort ();
  	goto loop;
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	obj = ptr->u.cdr;
  	cdr_count++;
=>	if (cdr_count == mark_object_loop_halt)
  	  emacs_abort ();
  	goto loop;
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	ptr->gcmarkbit = 1;
  	mark_object (ptr->function);
=>	mark_object (ptr->plist);
  	switch (ptr->redirect)
  	  {
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
       The distinction is used e.g. by Lisp_Process which places extra
       non-Lisp_Object fields at the end of the structure...  */
    for (i = 0; i < size; i++) /* ...and then mark its elements.  */
      mark_object (ptr->contents[i]);
  }
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	ptr->gcmarkbit = 1;
  	mark_object (ptr->function);
=>	mark_object (ptr->plist);
  	switch (ptr->redirect)
  	  {
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	mark_object (ptr->function);
  	mark_object (ptr->plist);
=>	switch (ptr->redirect)
  	  {
  	  case SYMBOL_PLAINVAL: mark_object (SYMBOL_VAL (ptr)); break;
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	obj = ptr->u.cdr;
  	cdr_count++;
=>	if (cdr_count == mark_object_loop_halt)
  	  emacs_abort ();
  	goto loop;
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	ptr->gcmarkbit = 1;
  	mark_object (ptr->function);
=>	mark_object (ptr->plist);
  	switch (ptr->redirect)
  	  {
/home/wasa/code/emacsen/emacs-24.5/src/alloc.c
  	obj = ptr->u.cdr;
  	cdr_count++;
=>	if (cdr_count == mark_object_loop_halt)
  	  emacs_abort ();
  	goto loop;
```

Looks like a nasty bug that got fixed in 25.1.  What Emacs are you experiencing this with?

**Comment by edkolev** [comment]
It's `GNU Emacs 25.2.1 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G1217)) of 2017-05-10`.

On linux, I don't observe the issue with `GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu) of 2017-01-03`

**Comment by edkolev** [comment]
I can't reproduce the coredump as easily after recompiling (via homebrew). After recompiling, I get the coredump less often -- roughly once out of ten times.

**Comment by wasamasa** [comment]
Oh well.  Do you consider your PR ready then?

**Comment by edkolev** [comment]
Yes, I think the PR is ready. I'll create a new issue in case I get more info on the coredump.

For the record, I'm sharing all I know about the coredump issue - I'm uploading an screenshot I took with an ERT error (failed test) - at the time when I could reproduce the coredump in terminal 100% of the times, I was sometimes getting this ERT error in the GUI emacs:

screen shot 2017-06-01 at 09 21 11

Commenting out all the tests related to "repeat" made the coredump-ing and GUI ERT error stop.

The user-error in the screenshot is produced by this line https://github.com/emacs-evil/evil/blob/dbaa700759a543a5240552697f458ad023074420/evil-repeat.el#L573

**Comment by wasamasa** [comment]
OK, I'll merge it then.

**Comment by edkolev** [comment]
Thanks!

**Comment by edkolev** [comment]
For the record, here's a CI build failure with a segfault https://travis-ci.org/emacs-evil/evil/jobs/241941724 (I hope this is a permanent url).

The output in the CI build is the same gibberish that I get right before the segfault.

**Comment by TheBB** [comment]
I've seen such segfaults before but only on Emacs 25 and only in terminal. That's why I made 25.1 an allowed failure on Travis. I'm not sure what's causing it.

**Pull request merged**
