### PR TITLE
Implement ]s and [s

### PR DESCRIPTION
**Pull request by wasamasa**
See #718.  This is a start and doesn't behave quite like Vim yet.  In Vim I don't get wraparound for `]s`, but for `[s`, there is no error when using it on a buffer without spelling mistakes and wraparound is customizable (`:help 'wrapscan'`).

edit: Looks like there's neither `ispell` nor `aspell` nor `hunspell` installed in the testing environment...

### CODE REVIEW

**Comment by wasamasa** [comment]
I consider this ready for use now.  While it still doesn't handle Vim's full range of spell checking (it knows bad and rare words as well...), it otherwise works as described in the linked ticket.

@TheBB Could you please test this to make sure I haven't overlooked any strange corner cases?

**Comment by wasamasa** [comment]
I consider this ready for use now.  While it still doesn't handle Vim's full range of spell checking (it knows bad and rare words as well...), it otherwise works as described in the linked ticket.

@TheBB Could you please test this to make sure I haven't overlooked any strange corner cases?

**Comment by TheBB** [comment]
This looks okay to me. Your dedication to replicating the vim behaviour is commendable, but I'm not convinced it's worth it to fly around looking for overlays instead of just using the higher level flyspell API and screw the differences.

Merged, at any rate. :-)

**Comment by wasamasa** [comment]
Flyspell doesn't provide a complete API, so I replicated it and added the missing parts.

**Pull request closed without merging**
