### PR TITLE
Remove support for Emacs < 24

### PR DESCRIPTION
**Pull request by TheBB**
The logical continuation of #770

### CODE REVIEW

**Comment by wasamasa** [comment]
Excellent, thanks!

**Comment by bmag** [comment]
Seems to have broken 3rd party packages that rely on, e.g. evil-nerd-commenter. (see https://gitter.im/syl20bnr/spacemacs?at=58a980ddaa800ee52cb60776)
I didn't check what else breaks

**Comment by wasamasa** [comment]
@bmag OK, that is indeed silly.  Why does that package even use Evil's wrapper of `called-interactively-p`?  It's not like it's trying to paper over Emacs 23 idiosyncracies...

**Comment by wasamasa** [comment]
According to [a simple search](https://github.com/search?q=evil-called-interactively-p&type=Code), this broke a few more:

- https://github.com/tarao/evil-plugins/blob/master/evil-operator-comment.el
- https://github.com/Dewdrops/evil-exchange/blob/master/evil-exchange.el
- https://github.com/roman/evil-paredit/blob/master/evil-paredit.el

**Comment by TheBB** [comment]
We can add back the functions with a deprecation warning perhaps?

**Comment by wasamasa** [comment]
Yeah, that would work, though I've considered handing in PRs to these packages instead.

**Comment by TheBB** [comment]
Okay, well I wrote https://github.com/emacs-evil/evil/pull/776 in the meantime.

**Pull request merged**
