### PR TITLE
Fix detection of newlines in evil-ex-substitute

### PR DESCRIPTION
**Pull request by justbur**
This addresses part of the problem in #969. I'll look at the rest later.

### CODE REVIEW

**Comment by wasamasa** [comment]
Hm, this doesn't improve things for me.  In a buffer with just "ABC" and no trailing newline I still get "ABC->->" after running `:%s/\([^][]*\)/\1->/g`. If I add a trailing newline, I get "ABC\n->->".

**Comment by justbur** [comment]
This corrects a different problem that I noticed while checking #969. The regex `[^][]*` is matching newlines without them being explicitly specified in the match string. This change detects this situation correctly. 

I added another commit to fix the issue you were referring to

**Comment by wasamasa** [comment]
Alright, thanks. Would you consider this done or do you reckon regression tests could be added? IIRC you stated last time there isn't much point to adding them.

**Comment by justbur** [comment]
Added a simple test for the regexp that matches newlines without containing one. I think it's done now

**Pull request merged**
