### PR TITLE
Fix parens in evil-ex-substitute

### PR DESCRIPTION
**Pull request by justbur**

### CODE REVIEW

**Comment by fosskers** [comment]
Without this spacemacs dies a firey death.

**Comment by justbur** [comment]
@wasamasa I'm merging it, because everything is broken without it.

**Comment by fosskers** [comment]
For anybody using spacemacs: if your editor boots into a weird state where things look spacemacsy but nothing functions as usual, you can use the following to manually rollback your packages:
```
M-x configuration-layer/rollback
```
where `M` is usually your `Alt` key.

**Comment by wasamasa** [comment]
@justbur That's fine, although it shouldn't have changed anything about the unbalanced parentheses thing as it got fixed in https://github.com/emacs-evil/evil/commit/7587f4ced289376c9b392efc7934bf8a89c8d1ef already.

**Comment by justbur** [comment]
@wasamasa Ah, I see you committed that after I opened this PR. 

I actually chose to include the next few forms in the `unwind-protect` statement because they seem to be more appropriate there, so there is a small change. Feel free to revert this if you want.

**Comment by hussein-aitlahcen** [comment]
As @fosskers, my spacemacs just died :P

**Comment by wasamasa** [comment]
@justbur It's OK, your change is what I've meant in https://github.com/emacs-evil/evil/issues/969#issuecomment-347772768.

**Comment by hussein-aitlahcen** [comment]
Seems like there is a missing parenthesis, or am I wrong ? [here](https://github.com/emacs-evil/evil/blob/1bba6116f3b29488a87503693e70a0bd2b5eaebe/evil-commands.el#L3486)

**Comment by justbur** [comment]
@hussein-aitlahcen not sure how you come to that conclusion, but the parens are balanced now.

**Comment by hussein-aitlahcen** [comment]
Never mind, I reverted and it's working.

**Pull request merged**
